//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocumentationProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocumentationProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cppref-docs-html-book.zip.
        /// </summary>
        public static string CppRefDocsArchive {
            get {
                return ResourceManager.GetString("CppRefDocsArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cppreference-docs/.
        /// </summary>
        public static string CppRefDocsDir {
            get {
                return ResourceManager.GetString("CppRefDocsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cppref-docs-releases.json.
        /// </summary>
        public static string CppRefDocsReleaseMetadata {
            get {
                return ResourceManager.GetString("CppRefDocsReleaseMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/PeterFeicht/cppreference-doc/releases.
        /// </summary>
        public static string CppRefDocsReleasesAPI {
            get {
                return ResourceManager.GetString("CppRefDocsReleasesAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\temp\cppref\temp-data\.
        /// </summary>
        public static string TempDataDir {
            get {
                return ResourceManager.GetString("TempDataDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\temp\cppref\user-data\.
        /// </summary>
        public static string UserDataDir {
            get {
                return ResourceManager.GetString("UserDataDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Xml_icon {
            get {
                object obj = ResourceManager.GetObject("Xml.icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
